exclude: ['README.md', 'assets/latex/', 'archive', 'venv']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2025fa-cmpt-713-x1/"
semcode: 1257
semester: "Fall 2025"
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 2"
midterm: "Oct 22"
instructor: anoop
tas:
  - name: Jackon de Faria
    email: jgd5
    officehour: 'TBD'
  - name: Enze Jiang
    email: eja42
    officehour: 'TBD'
  - name: Wanying Tian
    email: wta55
    officehour: 'TBD'
hwdates:
  - hw: "0"
    startdate: "Sep 8"
    deadline: "Sep 17"
    gracedays: "Sep 19"
  - hw: "1"
    startdate: "Sep 15"
    deadline: "Sep 29"
    gracedays: "Sep 19"
  - hw: "2"
    startdate: "Sep 29"
    deadline: "Oct 13"
    gracedays: "Oct 15"
  - hw: "3"
    startdate: "Oct 13"
    deadline: "Nov 3"
    gracedays: "Nov 5"
  - hw: "4"
    startdate: "Nov 3"
    deadline: "Nov 17"
    gracedays: "Nov 19"
  - hw: "project"
    startdate: "Nov 17"
    deadline: "Dec 5"
    time: "TBD"
    location: "TBD"
    proposal: "Nov 10"
